### ISSUE TITLE
Compiling to dll

### ISSUE THREAD

**Issue by ReBlast** [KillTheMule/nvim-rs#51]
Hey, a beginner in Rust here.
I was wondering about how would you compile this to an actual dll file so that Neovim can load it as a plugin.
I did try to set the `crate-type` to `cdylib` but this resulted in a warning saying `async fn main is unused`. And when plugin is loaded, nothing is printed to the console/log. Perhaps I'm loading it the wrong way.

(I'm not so sure whether this is the correct way of defining a plugin's entry point, I copied the code from one of the examples)

main.rs:
```rs
use tokio::fs::File as TokioFile;

use nvim_rs::{
  compat::tokio::Compat, create::tokio as create, Handler, Neovim, Value
};

#[derive(Clone)]
struct NeovimHandler {}

#[async_trait::async_trait]
impl Handler for NeovimHandler {
  type Writer = Compat<TokioFile>;

  async fn handle_request(
    &self,
    name: String,
    _args: Vec<Value>,
    _neovim: Neovim<Compat<TokioFile>>,
  ) -> Result<Value, Value> {
    match name.as_ref() {
      "ping" => Ok(Value::from("pong")),
      _ => unimplemented!(),
    }
  }
}

#[tokio::main]
async fn main() {
  println!("test");
  let handler: NeovimHandler = NeovimHandler {};
  let (nvim, io_handler) = create::new_parent(handler).await.unwrap();

  nvim.err_writeln("test").await.unwrap();
}
```

cargo.toml:
```toml
[package]
name = "..."
version = "0.1.0"
edition = "2021"

[lib]
path = "src/main.rs"
crate-type = ["cdylib"]

[[bin]]
name = "..."
path = "src/main.rs"

[dependencies]
async-trait = "0.1.77"
nvim-rs = { version = "0.7.0", features = ["use_tokio"] }
tokio = { version = "1", features = ["full"] }
```

lazy nvim:
```lua
return {
  name = 'myplugin',
  dev = true,
  lazy = false,
  dir = 'C:/Users/1/.local/nvim/plugins/myplugin.dll' -- built via `cargo build --release`
}
```
